// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: junction/rollup/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a12f95b833c221ad, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a12f95b833c221ad, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryCheckMonikerAvailabilityRequest struct {
	Moniker string `protobuf:"bytes,1,opt,name=moniker,proto3" json:"moniker,omitempty"`
}

func (m *QueryCheckMonikerAvailabilityRequest) Reset()         { *m = QueryCheckMonikerAvailabilityRequest{} }
func (m *QueryCheckMonikerAvailabilityRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCheckMonikerAvailabilityRequest) ProtoMessage()    {}
func (*QueryCheckMonikerAvailabilityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a12f95b833c221ad, []int{2}
}
func (m *QueryCheckMonikerAvailabilityRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCheckMonikerAvailabilityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCheckMonikerAvailabilityRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCheckMonikerAvailabilityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCheckMonikerAvailabilityRequest.Merge(m, src)
}
func (m *QueryCheckMonikerAvailabilityRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCheckMonikerAvailabilityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCheckMonikerAvailabilityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCheckMonikerAvailabilityRequest proto.InternalMessageInfo

func (m *QueryCheckMonikerAvailabilityRequest) GetMoniker() string {
	if m != nil {
		return m.Moniker
	}
	return ""
}

type QueryCheckMonikerAvailabilityResponse struct {
	IsAvailable bool `protobuf:"varint,1,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
}

func (m *QueryCheckMonikerAvailabilityResponse) Reset()         { *m = QueryCheckMonikerAvailabilityResponse{} }
func (m *QueryCheckMonikerAvailabilityResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCheckMonikerAvailabilityResponse) ProtoMessage()    {}
func (*QueryCheckMonikerAvailabilityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a12f95b833c221ad, []int{3}
}
func (m *QueryCheckMonikerAvailabilityResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCheckMonikerAvailabilityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCheckMonikerAvailabilityResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCheckMonikerAvailabilityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCheckMonikerAvailabilityResponse.Merge(m, src)
}
func (m *QueryCheckMonikerAvailabilityResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCheckMonikerAvailabilityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCheckMonikerAvailabilityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCheckMonikerAvailabilityResponse proto.InternalMessageInfo

func (m *QueryCheckMonikerAvailabilityResponse) GetIsAvailable() bool {
	if m != nil {
		return m.IsAvailable
	}
	return false
}

type QueryGetRollupInfoRequest struct {
	RollupId string `protobuf:"bytes,1,opt,name=rollupId,proto3" json:"rollupId,omitempty"`
}

func (m *QueryGetRollupInfoRequest) Reset()         { *m = QueryGetRollupInfoRequest{} }
func (m *QueryGetRollupInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetRollupInfoRequest) ProtoMessage()    {}
func (*QueryGetRollupInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a12f95b833c221ad, []int{4}
}
func (m *QueryGetRollupInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRollupInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRollupInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRollupInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRollupInfoRequest.Merge(m, src)
}
func (m *QueryGetRollupInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRollupInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRollupInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRollupInfoRequest proto.InternalMessageInfo

func (m *QueryGetRollupInfoRequest) GetRollupId() string {
	if m != nil {
		return m.RollupId
	}
	return ""
}

type QueryGetRollupInfoResponse struct {
	RollupInfo *RollupMetadata `protobuf:"bytes,1,opt,name=rollupInfo,proto3" json:"rollupInfo,omitempty"`
}

func (m *QueryGetRollupInfoResponse) Reset()         { *m = QueryGetRollupInfoResponse{} }
func (m *QueryGetRollupInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetRollupInfoResponse) ProtoMessage()    {}
func (*QueryGetRollupInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a12f95b833c221ad, []int{5}
}
func (m *QueryGetRollupInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRollupInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRollupInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRollupInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRollupInfoResponse.Merge(m, src)
}
func (m *QueryGetRollupInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRollupInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRollupInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRollupInfoResponse proto.InternalMessageInfo

func (m *QueryGetRollupInfoResponse) GetRollupInfo() *RollupMetadata {
	if m != nil {
		return m.RollupInfo
	}
	return nil
}

type QueryGetRollupsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryGetRollupsRequest) Reset()         { *m = QueryGetRollupsRequest{} }
func (m *QueryGetRollupsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetRollupsRequest) ProtoMessage()    {}
func (*QueryGetRollupsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a12f95b833c221ad, []int{6}
}
func (m *QueryGetRollupsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRollupsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRollupsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRollupsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRollupsRequest.Merge(m, src)
}
func (m *QueryGetRollupsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRollupsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRollupsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRollupsRequest proto.InternalMessageInfo

func (m *QueryGetRollupsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetRollupsResponse struct {
	Rollups    []RollupMetadata    `protobuf:"bytes,1,rep,name=rollups,proto3" json:"rollups"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryGetRollupsResponse) Reset()         { *m = QueryGetRollupsResponse{} }
func (m *QueryGetRollupsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetRollupsResponse) ProtoMessage()    {}
func (*QueryGetRollupsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a12f95b833c221ad, []int{7}
}
func (m *QueryGetRollupsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRollupsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRollupsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRollupsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRollupsResponse.Merge(m, src)
}
func (m *QueryGetRollupsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRollupsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRollupsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRollupsResponse proto.InternalMessageInfo

func (m *QueryGetRollupsResponse) GetRollups() []RollupMetadata {
	if m != nil {
		return m.Rollups
	}
	return nil
}

func (m *QueryGetRollupsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetRollupByMonikerRequest struct {
	Moniker string `protobuf:"bytes,1,opt,name=moniker,proto3" json:"moniker,omitempty"`
}

func (m *QueryGetRollupByMonikerRequest) Reset()         { *m = QueryGetRollupByMonikerRequest{} }
func (m *QueryGetRollupByMonikerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetRollupByMonikerRequest) ProtoMessage()    {}
func (*QueryGetRollupByMonikerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a12f95b833c221ad, []int{8}
}
func (m *QueryGetRollupByMonikerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRollupByMonikerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRollupByMonikerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRollupByMonikerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRollupByMonikerRequest.Merge(m, src)
}
func (m *QueryGetRollupByMonikerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRollupByMonikerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRollupByMonikerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRollupByMonikerRequest proto.InternalMessageInfo

func (m *QueryGetRollupByMonikerRequest) GetMoniker() string {
	if m != nil {
		return m.Moniker
	}
	return ""
}

type QueryGetRollupByMonikerResponse struct {
	RollupInfo *RollupMetadata `protobuf:"bytes,1,opt,name=rollupInfo,proto3" json:"rollupInfo,omitempty"`
}

func (m *QueryGetRollupByMonikerResponse) Reset()         { *m = QueryGetRollupByMonikerResponse{} }
func (m *QueryGetRollupByMonikerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetRollupByMonikerResponse) ProtoMessage()    {}
func (*QueryGetRollupByMonikerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a12f95b833c221ad, []int{9}
}
func (m *QueryGetRollupByMonikerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRollupByMonikerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRollupByMonikerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRollupByMonikerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRollupByMonikerResponse.Merge(m, src)
}
func (m *QueryGetRollupByMonikerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRollupByMonikerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRollupByMonikerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRollupByMonikerResponse proto.InternalMessageInfo

func (m *QueryGetRollupByMonikerResponse) GetRollupInfo() *RollupMetadata {
	if m != nil {
		return m.RollupInfo
	}
	return nil
}

type QueryGetBatchInfoRequest struct {
	RollupId string `protobuf:"bytes,1,opt,name=rollupId,proto3" json:"rollupId,omitempty"`
	BatchNo  uint64 `protobuf:"varint,2,opt,name=batchNo,proto3" json:"batchNo,omitempty"`
}

func (m *QueryGetBatchInfoRequest) Reset()         { *m = QueryGetBatchInfoRequest{} }
func (m *QueryGetBatchInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetBatchInfoRequest) ProtoMessage()    {}
func (*QueryGetBatchInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a12f95b833c221ad, []int{10}
}
func (m *QueryGetBatchInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetBatchInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetBatchInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetBatchInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetBatchInfoRequest.Merge(m, src)
}
func (m *QueryGetBatchInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetBatchInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetBatchInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetBatchInfoRequest proto.InternalMessageInfo

func (m *QueryGetBatchInfoRequest) GetRollupId() string {
	if m != nil {
		return m.RollupId
	}
	return ""
}

func (m *QueryGetBatchInfoRequest) GetBatchNo() uint64 {
	if m != nil {
		return m.BatchNo
	}
	return 0
}

type QueryGetBatchInfoResponse struct {
	BatchInfo *Batch `protobuf:"bytes,1,opt,name=batchInfo,proto3" json:"batchInfo,omitempty"`
}

func (m *QueryGetBatchInfoResponse) Reset()         { *m = QueryGetBatchInfoResponse{} }
func (m *QueryGetBatchInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetBatchInfoResponse) ProtoMessage()    {}
func (*QueryGetBatchInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a12f95b833c221ad, []int{11}
}
func (m *QueryGetBatchInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetBatchInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetBatchInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetBatchInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetBatchInfoResponse.Merge(m, src)
}
func (m *QueryGetBatchInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetBatchInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetBatchInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetBatchInfoResponse proto.InternalMessageInfo

func (m *QueryGetBatchInfoResponse) GetBatchInfo() *Batch {
	if m != nil {
		return m.BatchInfo
	}
	return nil
}

type QueryGetAllBatchesRequest struct {
	RollupId string `protobuf:"bytes,1,opt,name=rollupId,proto3" json:"rollupId,omitempty"`
	// Types that are valid to be assigned to XOffset:
	//	*QueryGetAllBatchesRequest_Offset
	XOffset isQueryGetAllBatchesRequest_XOffset `protobuf_oneof:"_offset"`
	// Types that are valid to be assigned to XLimit:
	//	*QueryGetAllBatchesRequest_Limit
	XLimit isQueryGetAllBatchesRequest_XLimit `protobuf_oneof:"_limit"`
	// Types that are valid to be assigned to XOrder:
	//	*QueryGetAllBatchesRequest_Order
	XOrder isQueryGetAllBatchesRequest_XOrder `protobuf_oneof:"_order"`
}

func (m *QueryGetAllBatchesRequest) Reset()         { *m = QueryGetAllBatchesRequest{} }
func (m *QueryGetAllBatchesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetAllBatchesRequest) ProtoMessage()    {}
func (*QueryGetAllBatchesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a12f95b833c221ad, []int{12}
}
func (m *QueryGetAllBatchesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAllBatchesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAllBatchesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAllBatchesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAllBatchesRequest.Merge(m, src)
}
func (m *QueryGetAllBatchesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAllBatchesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAllBatchesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAllBatchesRequest proto.InternalMessageInfo

type isQueryGetAllBatchesRequest_XOffset interface {
	isQueryGetAllBatchesRequest_XOffset()
	MarshalTo([]byte) (int, error)
	Size() int
}
type isQueryGetAllBatchesRequest_XLimit interface {
	isQueryGetAllBatchesRequest_XLimit()
	MarshalTo([]byte) (int, error)
	Size() int
}
type isQueryGetAllBatchesRequest_XOrder interface {
	isQueryGetAllBatchesRequest_XOrder()
	MarshalTo([]byte) (int, error)
	Size() int
}

type QueryGetAllBatchesRequest_Offset struct {
	Offset uint64 `protobuf:"varint,2,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
}
type QueryGetAllBatchesRequest_Limit struct {
	Limit uint64 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
}
type QueryGetAllBatchesRequest_Order struct {
	Order string `protobuf:"bytes,4,opt,name=order,proto3,oneof" json:"order,omitempty"`
}

func (*QueryGetAllBatchesRequest_Offset) isQueryGetAllBatchesRequest_XOffset() {}
func (*QueryGetAllBatchesRequest_Limit) isQueryGetAllBatchesRequest_XLimit()   {}
func (*QueryGetAllBatchesRequest_Order) isQueryGetAllBatchesRequest_XOrder()   {}

func (m *QueryGetAllBatchesRequest) GetXOffset() isQueryGetAllBatchesRequest_XOffset {
	if m != nil {
		return m.XOffset
	}
	return nil
}
func (m *QueryGetAllBatchesRequest) GetXLimit() isQueryGetAllBatchesRequest_XLimit {
	if m != nil {
		return m.XLimit
	}
	return nil
}
func (m *QueryGetAllBatchesRequest) GetXOrder() isQueryGetAllBatchesRequest_XOrder {
	if m != nil {
		return m.XOrder
	}
	return nil
}

func (m *QueryGetAllBatchesRequest) GetRollupId() string {
	if m != nil {
		return m.RollupId
	}
	return ""
}

func (m *QueryGetAllBatchesRequest) GetOffset() uint64 {
	if x, ok := m.GetXOffset().(*QueryGetAllBatchesRequest_Offset); ok {
		return x.Offset
	}
	return 0
}

func (m *QueryGetAllBatchesRequest) GetLimit() uint64 {
	if x, ok := m.GetXLimit().(*QueryGetAllBatchesRequest_Limit); ok {
		return x.Limit
	}
	return 0
}

func (m *QueryGetAllBatchesRequest) GetOrder() string {
	if x, ok := m.GetXOrder().(*QueryGetAllBatchesRequest_Order); ok {
		return x.Order
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*QueryGetAllBatchesRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*QueryGetAllBatchesRequest_Offset)(nil),
		(*QueryGetAllBatchesRequest_Limit)(nil),
		(*QueryGetAllBatchesRequest_Order)(nil),
	}
}

type QueryGetAllBatchesResponse struct {
	Batch  []Batch `protobuf:"bytes,1,rep,name=batch,proto3" json:"batch"`
	Total  uint64  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Offset uint64  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  uint64  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Order  string  `protobuf:"bytes,5,opt,name=order,proto3" json:"order,omitempty"`
}

func (m *QueryGetAllBatchesResponse) Reset()         { *m = QueryGetAllBatchesResponse{} }
func (m *QueryGetAllBatchesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetAllBatchesResponse) ProtoMessage()    {}
func (*QueryGetAllBatchesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a12f95b833c221ad, []int{13}
}
func (m *QueryGetAllBatchesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAllBatchesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAllBatchesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAllBatchesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAllBatchesResponse.Merge(m, src)
}
func (m *QueryGetAllBatchesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAllBatchesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAllBatchesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAllBatchesResponse proto.InternalMessageInfo

func (m *QueryGetAllBatchesResponse) GetBatch() []Batch {
	if m != nil {
		return m.Batch
	}
	return nil
}

func (m *QueryGetAllBatchesResponse) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *QueryGetAllBatchesResponse) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *QueryGetAllBatchesResponse) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *QueryGetAllBatchesResponse) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "junction.rollup.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "junction.rollup.QueryParamsResponse")
	proto.RegisterType((*QueryCheckMonikerAvailabilityRequest)(nil), "junction.rollup.QueryCheckMonikerAvailabilityRequest")
	proto.RegisterType((*QueryCheckMonikerAvailabilityResponse)(nil), "junction.rollup.QueryCheckMonikerAvailabilityResponse")
	proto.RegisterType((*QueryGetRollupInfoRequest)(nil), "junction.rollup.QueryGetRollupInfoRequest")
	proto.RegisterType((*QueryGetRollupInfoResponse)(nil), "junction.rollup.QueryGetRollupInfoResponse")
	proto.RegisterType((*QueryGetRollupsRequest)(nil), "junction.rollup.QueryGetRollupsRequest")
	proto.RegisterType((*QueryGetRollupsResponse)(nil), "junction.rollup.QueryGetRollupsResponse")
	proto.RegisterType((*QueryGetRollupByMonikerRequest)(nil), "junction.rollup.QueryGetRollupByMonikerRequest")
	proto.RegisterType((*QueryGetRollupByMonikerResponse)(nil), "junction.rollup.QueryGetRollupByMonikerResponse")
	proto.RegisterType((*QueryGetBatchInfoRequest)(nil), "junction.rollup.QueryGetBatchInfoRequest")
	proto.RegisterType((*QueryGetBatchInfoResponse)(nil), "junction.rollup.QueryGetBatchInfoResponse")
	proto.RegisterType((*QueryGetAllBatchesRequest)(nil), "junction.rollup.QueryGetAllBatchesRequest")
	proto.RegisterType((*QueryGetAllBatchesResponse)(nil), "junction.rollup.QueryGetAllBatchesResponse")
}

func init() { proto.RegisterFile("junction/rollup/query.proto", fileDescriptor_a12f95b833c221ad) }

var fileDescriptor_a12f95b833c221ad = []byte{
	// 954 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0x4d, 0x6f, 0x1b, 0x45,
	0x18, 0xc7, 0x3d, 0x69, 0xec, 0xc4, 0x4f, 0x8b, 0x10, 0x83, 0x95, 0x9a, 0x05, 0x39, 0xb0, 0xb4,
	0xb4, 0x4d, 0xc5, 0x6e, 0x13, 0x4a, 0x91, 0x2a, 0xa1, 0x92, 0x05, 0x9a, 0xa4, 0x52, 0x43, 0xb2,
	0x47, 0x24, 0x64, 0x66, 0x9d, 0xc9, 0x66, 0xc8, 0x7a, 0xc7, 0xdd, 0x1d, 0x17, 0xac, 0xa8, 0x17,
	0x0e, 0x9c, 0x91, 0x38, 0x70, 0x45, 0xe2, 0x82, 0xb8, 0xc0, 0x85, 0x4f, 0xc0, 0xa5, 0xc7, 0x4a,
	0x5c, 0x10, 0x07, 0x84, 0x12, 0x24, 0xc4, 0xb7, 0x40, 0x3b, 0x2f, 0x7e, 0x5b, 0xc7, 0x5e, 0x4b,
	0x5c, 0xda, 0x9d, 0x79, 0xde, 0x7e, 0xcf, 0xcc, 0x7f, 0x1e, 0x07, 0x5e, 0xfe, 0xac, 0x1b, 0xb7,
	0x04, 0xe3, 0xb1, 0x9b, 0xf0, 0x28, 0xea, 0x76, 0xdc, 0x47, 0x5d, 0x9a, 0xf4, 0x9c, 0x4e, 0xc2,
	0x05, 0xc7, 0xcf, 0x1b, 0xa3, 0xa3, 0x8c, 0xd6, 0x0b, 0xa4, 0xcd, 0x62, 0xee, 0xca, 0x7f, 0x95,
	0x8f, 0x55, 0x0b, 0x79, 0xc8, 0xe5, 0xa7, 0x9b, 0x7d, 0xe9, 0xdd, 0x57, 0x42, 0xce, 0xc3, 0x88,
	0xba, 0xa4, 0xc3, 0x5c, 0x12, 0xc7, 0x5c, 0x90, 0x2c, 0x4d, 0xaa, 0xad, 0x6b, 0x2d, 0x9e, 0xb6,
	0x79, 0xea, 0x06, 0x24, 0xa5, 0xaa, 0xa0, 0xfb, 0x78, 0x3d, 0xa0, 0x82, 0xac, 0xbb, 0x1d, 0x12,
	0xb2, 0x58, 0x3a, 0x9b, 0x4c, 0xe3, 0x80, 0x1d, 0x92, 0x90, 0xb6, 0xc9, 0x74, 0x75, 0xdc, 0xaa,
	0xfe, 0x6b, 0xb6, 0xa9, 0x20, 0x07, 0x44, 0x10, 0xed, 0x96, 0xeb, 0x32, 0x20, 0xa2, 0x75, 0xa4,
	0x8c, 0x76, 0x0d, 0xf0, 0x7e, 0xc6, 0xb0, 0x27, 0x13, 0xfb, 0xf4, 0x51, 0x97, 0xa6, 0xc2, 0xde,
	0x87, 0x17, 0x47, 0x76, 0xd3, 0x0e, 0x8f, 0x53, 0x8a, 0xef, 0x42, 0x45, 0x01, 0xd4, 0xd1, 0xab,
	0xe8, 0xfa, 0xc5, 0x8d, 0xcb, 0xce, 0xd8, 0x19, 0x39, 0x2a, 0xc0, 0xab, 0x3e, 0xfd, 0x73, 0xb5,
	0xf4, 0xc3, 0x3f, 0x3f, 0xaf, 0x21, 0x5f, 0x47, 0xd8, 0xef, 0xc1, 0x15, 0x99, 0xf2, 0xfd, 0x23,
	0xda, 0x3a, 0x7e, 0xc8, 0x63, 0x76, 0x4c, 0x93, 0xcd, 0xc7, 0x84, 0x45, 0x24, 0x60, 0x11, 0x13,
	0x3d, 0x5d, 0x1a, 0xd7, 0x61, 0xa9, 0xad, 0xac, 0xb2, 0x48, 0xd5, 0x37, 0x4b, 0xfb, 0x01, 0x5c,
	0x9d, 0x91, 0x41, 0x63, 0xbe, 0x06, 0x97, 0x58, 0xda, 0x24, 0xca, 0x14, 0x51, 0x99, 0x67, 0xd9,
	0xbf, 0xc8, 0xd2, 0x4d, 0xb3, 0x65, 0xbf, 0x03, 0x2f, 0xc9, 0x5c, 0x5b, 0x54, 0xf8, 0x92, 0x7c,
	0x27, 0x3e, 0xe4, 0x06, 0xc1, 0x82, 0x65, 0xd5, 0xce, 0xce, 0x81, 0x66, 0xe8, 0xaf, 0xed, 0x4f,
	0xc0, 0x9a, 0x14, 0xa8, 0x2b, 0xdf, 0x03, 0x48, 0xfa, 0xbb, 0xfa, 0x90, 0x56, 0x73, 0x87, 0xa4,
	0x02, 0x1f, 0xea, 0x5b, 0xf2, 0x87, 0x42, 0xec, 0x4f, 0x61, 0x65, 0x34, 0xbd, 0xb9, 0x12, 0x7c,
	0x1f, 0x60, 0x20, 0x0f, 0x9d, 0xfa, 0x0d, 0x47, 0x69, 0xc9, 0xc9, 0xb4, 0xe4, 0x28, 0xf1, 0x6a,
	0x2d, 0x39, 0x7b, 0x24, 0xa4, 0x3a, 0xd6, 0x1f, 0x8a, 0xb4, 0xbf, 0x47, 0x70, 0x39, 0x57, 0xa2,
	0x8f, 0xbf, 0xa4, 0x58, 0xb2, 0x0b, 0xbe, 0x50, 0x80, 0xdd, 0x5b, 0xcc, 0x2e, 0xda, 0x37, 0x51,
	0x78, 0x6b, 0x04, 0x72, 0x41, 0x42, 0x5e, 0x9b, 0x09, 0xa9, 0xaa, 0x8f, 0x50, 0xde, 0x85, 0xc6,
	0x28, 0xa4, 0xd7, 0xd3, 0x37, 0x3e, 0x5b, 0x27, 0x01, 0xac, 0x9e, 0x1b, 0xfb, 0x7f, 0xdd, 0xd3,
	0x1e, 0xd4, 0x4d, 0x0d, 0x2f, 0x7b, 0x4d, 0x05, 0xe5, 0x93, 0x51, 0xcb, 0xd7, 0xb7, 0xcb, 0xe5,
	0xe9, 0x2c, 0xfa, 0x66, 0x69, 0xef, 0x0f, 0x14, 0x39, 0x94, 0x51, 0xf3, 0xde, 0x86, 0x6a, 0x60,
	0x36, 0x35, 0xee, 0x4a, 0x0e, 0x57, 0x86, 0xf9, 0x03, 0x47, 0xfb, 0x3b, 0x34, 0xc8, 0xb9, 0x19,
	0x45, 0xd2, 0x4e, 0xd3, 0x62, 0x98, 0x15, 0x7e, 0x78, 0x98, 0x52, 0xa1, 0x28, 0xb7, 0x4b, 0xbe,
	0x5e, 0xe3, 0x15, 0x28, 0x47, 0xac, 0xcd, 0x44, 0xfd, 0x82, 0x34, 0x20, 0x5f, 0x2d, 0xb3, 0x7d,
	0x9e, 0x1c, 0xd0, 0xa4, 0xbe, 0x98, 0xa5, 0xda, 0x5e, 0xf0, 0xd5, 0xd2, 0xab, 0xc2, 0x52, 0x53,
	0x85, 0x7a, 0xcb, 0x50, 0x69, 0x4a, 0x67, 0xf9, 0x25, 0xcd, 0xf6, 0x8f, 0x68, 0xf0, 0x9e, 0x86,
	0x11, 0x75, 0xdf, 0x1b, 0x50, 0x96, 0xed, 0x68, 0x39, 0x9e, 0xd3, 0xb3, 0x56, 0xa1, 0x72, 0xc5,
	0x35, 0x28, 0x0b, 0x2e, 0x48, 0xa4, 0x0f, 0x58, 0x2d, 0xf0, 0x4a, 0xbf, 0x23, 0x09, 0xde, 0xef,
	0xa7, 0x66, 0xfa, 0x59, 0x54, 0xde, 0xaa, 0x9b, 0x9a, 0xe9, 0xa6, 0x2c, 0x0f, 0x46, 0x2d, 0x36,
	0xfe, 0xad, 0x42, 0x59, 0xc2, 0xe2, 0xaf, 0x10, 0x54, 0xd4, 0xa8, 0xc3, 0xaf, 0xe7, 0x98, 0xf2,
	0xf3, 0xd4, 0xba, 0x32, 0xdd, 0x49, 0x75, 0x6b, 0xaf, 0x7f, 0xf9, 0xdb, 0xdf, 0xdf, 0x2c, 0xdc,
	0xc4, 0x37, 0x5c, 0xc2, 0x92, 0xd6, 0x11, 0x61, 0x71, 0xfa, 0x66, 0x4c, 0xc5, 0xe7, 0x3c, 0x39,
	0x76, 0x27, 0xff, 0x10, 0xe0, 0x3f, 0x10, 0xd4, 0xcf, 0x9b, 0x87, 0xf8, 0xed, 0xc9, 0x55, 0x67,
	0x4c, 0x60, 0xeb, 0xce, 0xbc, 0x61, 0x1a, 0xff, 0x23, 0x89, 0xbf, 0x83, 0xb7, 0x0a, 0xe0, 0xb7,
	0xb2, 0x64, 0x4d, 0xfd, 0x62, 0xcd, 0xa8, 0x96, 0xe9, 0xdc, 0x13, 0xbd, 0xfb, 0x04, 0xff, 0x84,
	0xe0, 0xb9, 0x91, 0x39, 0x8b, 0xd7, 0x26, 0xa3, 0x4d, 0x9a, 0xe2, 0xd6, 0xcd, 0x42, 0xbe, 0x9a,
	0xfd, 0x43, 0xc9, 0x7e, 0x0f, 0xbf, 0x5b, 0x80, 0x3d, 0xa4, 0xa2, 0xa9, 0x7f, 0x69, 0x59, 0x7c,
	0xc8, 0xdd, 0x13, 0xf3, 0x6c, 0x9e, 0xe0, 0x6f, 0x11, 0xc0, 0x60, 0xae, 0xe2, 0x6b, 0x33, 0x10,
	0xfa, 0xfa, 0xb8, 0x3e, 0xdb, 0x51, 0x83, 0xde, 0x91, 0xa0, 0xb7, 0xb0, 0x33, 0x17, 0x68, 0x8a,
	0x7f, 0x45, 0x80, 0xf3, 0x03, 0x11, 0xbb, 0x33, 0x0a, 0x8f, 0x8f, 0x5d, 0xeb, 0x56, 0xf1, 0x00,
	0x4d, 0xfc, 0x40, 0x12, 0x7f, 0x80, 0xbd, 0xf9, 0x8e, 0x36, 0xe8, 0x19, 0x79, 0x0c, 0x29, 0xe2,
	0x17, 0x04, 0x97, 0x86, 0x07, 0x24, 0xbe, 0x71, 0x2e, 0xce, 0xf8, 0x58, 0xb6, 0xd6, 0x8a, 0xb8,
	0x6a, 0xe6, 0x5d, 0xc9, 0xbc, 0x8d, 0xef, 0x17, 0x64, 0x96, 0x93, 0x67, 0x5c, 0x0d, 0xee, 0x89,
	0x9e, 0xed, 0x7d, 0x25, 0x0f, 0x26, 0xdc, 0x14, 0x25, 0xe7, 0x26, 0xf5, 0x14, 0x25, 0xe7, 0x47,
	0xe6, 0xdc, 0x4a, 0x26, 0x51, 0xa4, 0xf0, 0x69, 0x3a, 0xc4, 0xee, 0xed, 0x3e, 0x3d, 0x6d, 0xa0,
	0x67, 0xa7, 0x0d, 0xf4, 0xd7, 0x69, 0x03, 0x7d, 0x7d, 0xd6, 0x28, 0x3d, 0x3b, 0x6b, 0x94, 0x7e,
	0x3f, 0x6b, 0x94, 0x3e, 0xbe, 0x1d, 0x32, 0x71, 0xd4, 0x0d, 0x9c, 0x16, 0x6f, 0x4f, 0x2b, 0xf1,
	0x85, 0x29, 0x22, 0x7a, 0x1d, 0x9a, 0x06, 0x15, 0xf9, 0xe7, 0xe6, 0x5b, 0xff, 0x05, 0x00, 0x00,
	0xff, 0xff, 0x32, 0x76, 0x75, 0x04, 0x73, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of CheckMonikerAvailability items.
	CheckMonikerAvailability(ctx context.Context, in *QueryCheckMonikerAvailabilityRequest, opts ...grpc.CallOption) (*QueryCheckMonikerAvailabilityResponse, error)
	// Queries a list of GetRollupInfo items.
	GetRollupInfo(ctx context.Context, in *QueryGetRollupInfoRequest, opts ...grpc.CallOption) (*QueryGetRollupInfoResponse, error)
	// Queries a list of GetRollups items.
	GetRollups(ctx context.Context, in *QueryGetRollupsRequest, opts ...grpc.CallOption) (*QueryGetRollupsResponse, error)
	// Queries a list of GetRollupByMoniker items.
	GetRollupByMoniker(ctx context.Context, in *QueryGetRollupByMonikerRequest, opts ...grpc.CallOption) (*QueryGetRollupByMonikerResponse, error)
	// Queries a list of GetBatchInfo items.
	GetBatchInfo(ctx context.Context, in *QueryGetBatchInfoRequest, opts ...grpc.CallOption) (*QueryGetBatchInfoResponse, error)
	// Queries a list of GetAllBatches items.
	GetAllBatches(ctx context.Context, in *QueryGetAllBatchesRequest, opts ...grpc.CallOption) (*QueryGetAllBatchesResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/junction.rollup.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CheckMonikerAvailability(ctx context.Context, in *QueryCheckMonikerAvailabilityRequest, opts ...grpc.CallOption) (*QueryCheckMonikerAvailabilityResponse, error) {
	out := new(QueryCheckMonikerAvailabilityResponse)
	err := c.cc.Invoke(ctx, "/junction.rollup.Query/CheckMonikerAvailability", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetRollupInfo(ctx context.Context, in *QueryGetRollupInfoRequest, opts ...grpc.CallOption) (*QueryGetRollupInfoResponse, error) {
	out := new(QueryGetRollupInfoResponse)
	err := c.cc.Invoke(ctx, "/junction.rollup.Query/GetRollupInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetRollups(ctx context.Context, in *QueryGetRollupsRequest, opts ...grpc.CallOption) (*QueryGetRollupsResponse, error) {
	out := new(QueryGetRollupsResponse)
	err := c.cc.Invoke(ctx, "/junction.rollup.Query/GetRollups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetRollupByMoniker(ctx context.Context, in *QueryGetRollupByMonikerRequest, opts ...grpc.CallOption) (*QueryGetRollupByMonikerResponse, error) {
	out := new(QueryGetRollupByMonikerResponse)
	err := c.cc.Invoke(ctx, "/junction.rollup.Query/GetRollupByMoniker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetBatchInfo(ctx context.Context, in *QueryGetBatchInfoRequest, opts ...grpc.CallOption) (*QueryGetBatchInfoResponse, error) {
	out := new(QueryGetBatchInfoResponse)
	err := c.cc.Invoke(ctx, "/junction.rollup.Query/GetBatchInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetAllBatches(ctx context.Context, in *QueryGetAllBatchesRequest, opts ...grpc.CallOption) (*QueryGetAllBatchesResponse, error) {
	out := new(QueryGetAllBatchesResponse)
	err := c.cc.Invoke(ctx, "/junction.rollup.Query/GetAllBatches", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of CheckMonikerAvailability items.
	CheckMonikerAvailability(context.Context, *QueryCheckMonikerAvailabilityRequest) (*QueryCheckMonikerAvailabilityResponse, error)
	// Queries a list of GetRollupInfo items.
	GetRollupInfo(context.Context, *QueryGetRollupInfoRequest) (*QueryGetRollupInfoResponse, error)
	// Queries a list of GetRollups items.
	GetRollups(context.Context, *QueryGetRollupsRequest) (*QueryGetRollupsResponse, error)
	// Queries a list of GetRollupByMoniker items.
	GetRollupByMoniker(context.Context, *QueryGetRollupByMonikerRequest) (*QueryGetRollupByMonikerResponse, error)
	// Queries a list of GetBatchInfo items.
	GetBatchInfo(context.Context, *QueryGetBatchInfoRequest) (*QueryGetBatchInfoResponse, error)
	// Queries a list of GetAllBatches items.
	GetAllBatches(context.Context, *QueryGetAllBatchesRequest) (*QueryGetAllBatchesResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) CheckMonikerAvailability(ctx context.Context, req *QueryCheckMonikerAvailabilityRequest) (*QueryCheckMonikerAvailabilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckMonikerAvailability not implemented")
}
func (*UnimplementedQueryServer) GetRollupInfo(ctx context.Context, req *QueryGetRollupInfoRequest) (*QueryGetRollupInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRollupInfo not implemented")
}
func (*UnimplementedQueryServer) GetRollups(ctx context.Context, req *QueryGetRollupsRequest) (*QueryGetRollupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRollups not implemented")
}
func (*UnimplementedQueryServer) GetRollupByMoniker(ctx context.Context, req *QueryGetRollupByMonikerRequest) (*QueryGetRollupByMonikerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRollupByMoniker not implemented")
}
func (*UnimplementedQueryServer) GetBatchInfo(ctx context.Context, req *QueryGetBatchInfoRequest) (*QueryGetBatchInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBatchInfo not implemented")
}
func (*UnimplementedQueryServer) GetAllBatches(ctx context.Context, req *QueryGetAllBatchesRequest) (*QueryGetAllBatchesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllBatches not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/junction.rollup.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CheckMonikerAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCheckMonikerAvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CheckMonikerAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/junction.rollup.Query/CheckMonikerAvailability",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CheckMonikerAvailability(ctx, req.(*QueryCheckMonikerAvailabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetRollupInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetRollupInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetRollupInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/junction.rollup.Query/GetRollupInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetRollupInfo(ctx, req.(*QueryGetRollupInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetRollups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetRollupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetRollups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/junction.rollup.Query/GetRollups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetRollups(ctx, req.(*QueryGetRollupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetRollupByMoniker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetRollupByMonikerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetRollupByMoniker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/junction.rollup.Query/GetRollupByMoniker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetRollupByMoniker(ctx, req.(*QueryGetRollupByMonikerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetBatchInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetBatchInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetBatchInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/junction.rollup.Query/GetBatchInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetBatchInfo(ctx, req.(*QueryGetBatchInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetAllBatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAllBatchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetAllBatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/junction.rollup.Query/GetAllBatches",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetAllBatches(ctx, req.(*QueryGetAllBatchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "junction.rollup.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "CheckMonikerAvailability",
			Handler:    _Query_CheckMonikerAvailability_Handler,
		},
		{
			MethodName: "GetRollupInfo",
			Handler:    _Query_GetRollupInfo_Handler,
		},
		{
			MethodName: "GetRollups",
			Handler:    _Query_GetRollups_Handler,
		},
		{
			MethodName: "GetRollupByMoniker",
			Handler:    _Query_GetRollupByMoniker_Handler,
		},
		{
			MethodName: "GetBatchInfo",
			Handler:    _Query_GetBatchInfo_Handler,
		},
		{
			MethodName: "GetAllBatches",
			Handler:    _Query_GetAllBatches_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "junction/rollup/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryCheckMonikerAvailabilityRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCheckMonikerAvailabilityRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCheckMonikerAvailabilityRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Moniker) > 0 {
		i -= len(m.Moniker)
		copy(dAtA[i:], m.Moniker)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Moniker)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryCheckMonikerAvailabilityResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCheckMonikerAvailabilityResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCheckMonikerAvailabilityResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsAvailable {
		i--
		if m.IsAvailable {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetRollupInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRollupInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRollupInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RollupId) > 0 {
		i -= len(m.RollupId)
		copy(dAtA[i:], m.RollupId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.RollupId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetRollupInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRollupInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRollupInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RollupInfo != nil {
		{
			size, err := m.RollupInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetRollupsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRollupsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRollupsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetRollupsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRollupsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRollupsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Rollups) > 0 {
		for iNdEx := len(m.Rollups) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Rollups[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetRollupByMonikerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRollupByMonikerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRollupByMonikerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Moniker) > 0 {
		i -= len(m.Moniker)
		copy(dAtA[i:], m.Moniker)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Moniker)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetRollupByMonikerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRollupByMonikerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRollupByMonikerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RollupInfo != nil {
		{
			size, err := m.RollupInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetBatchInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetBatchInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetBatchInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BatchNo != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.BatchNo))
		i--
		dAtA[i] = 0x10
	}
	if len(m.RollupId) > 0 {
		i -= len(m.RollupId)
		copy(dAtA[i:], m.RollupId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.RollupId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetBatchInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetBatchInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetBatchInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BatchInfo != nil {
		{
			size, err := m.BatchInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAllBatchesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAllBatchesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAllBatchesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XOrder != nil {
		{
			size := m.XOrder.Size()
			i -= size
			if _, err := m.XOrder.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.XLimit != nil {
		{
			size := m.XLimit.Size()
			i -= size
			if _, err := m.XLimit.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.XOffset != nil {
		{
			size := m.XOffset.Size()
			i -= size
			if _, err := m.XOffset.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if len(m.RollupId) > 0 {
		i -= len(m.RollupId)
		copy(dAtA[i:], m.RollupId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.RollupId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAllBatchesRequest_Offset) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAllBatchesRequest_Offset) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = encodeVarintQuery(dAtA, i, uint64(m.Offset))
	i--
	dAtA[i] = 0x10
	return len(dAtA) - i, nil
}
func (m *QueryGetAllBatchesRequest_Limit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAllBatchesRequest_Limit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = encodeVarintQuery(dAtA, i, uint64(m.Limit))
	i--
	dAtA[i] = 0x18
	return len(dAtA) - i, nil
}
func (m *QueryGetAllBatchesRequest_Order) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAllBatchesRequest_Order) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i -= len(m.Order)
	copy(dAtA[i:], m.Order)
	i = encodeVarintQuery(dAtA, i, uint64(len(m.Order)))
	i--
	dAtA[i] = 0x22
	return len(dAtA) - i, nil
}
func (m *QueryGetAllBatchesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAllBatchesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAllBatchesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Order) > 0 {
		i -= len(m.Order)
		copy(dAtA[i:], m.Order)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Order)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Limit != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Limit))
		i--
		dAtA[i] = 0x20
	}
	if m.Offset != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Offset))
		i--
		dAtA[i] = 0x18
	}
	if m.Total != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Total))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Batch) > 0 {
		for iNdEx := len(m.Batch) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Batch[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryCheckMonikerAvailabilityRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Moniker)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCheckMonikerAvailabilityResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IsAvailable {
		n += 2
	}
	return n
}

func (m *QueryGetRollupInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RollupId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetRollupInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RollupInfo != nil {
		l = m.RollupInfo.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetRollupsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetRollupsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Rollups) > 0 {
		for _, e := range m.Rollups {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetRollupByMonikerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Moniker)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetRollupByMonikerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RollupInfo != nil {
		l = m.RollupInfo.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetBatchInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RollupId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.BatchNo != 0 {
		n += 1 + sovQuery(uint64(m.BatchNo))
	}
	return n
}

func (m *QueryGetBatchInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BatchInfo != nil {
		l = m.BatchInfo.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetAllBatchesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RollupId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.XOffset != nil {
		n += m.XOffset.Size()
	}
	if m.XLimit != nil {
		n += m.XLimit.Size()
	}
	if m.XOrder != nil {
		n += m.XOrder.Size()
	}
	return n
}

func (m *QueryGetAllBatchesRequest_Offset) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovQuery(uint64(m.Offset))
	return n
}
func (m *QueryGetAllBatchesRequest_Limit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovQuery(uint64(m.Limit))
	return n
}
func (m *QueryGetAllBatchesRequest_Order) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Order)
	n += 1 + l + sovQuery(uint64(l))
	return n
}
func (m *QueryGetAllBatchesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Batch) > 0 {
		for _, e := range m.Batch {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Total != 0 {
		n += 1 + sovQuery(uint64(m.Total))
	}
	if m.Offset != 0 {
		n += 1 + sovQuery(uint64(m.Offset))
	}
	if m.Limit != 0 {
		n += 1 + sovQuery(uint64(m.Limit))
	}
	l = len(m.Order)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCheckMonikerAvailabilityRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCheckMonikerAvailabilityRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCheckMonikerAvailabilityRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Moniker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Moniker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCheckMonikerAvailabilityResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCheckMonikerAvailabilityResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCheckMonikerAvailabilityResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsAvailable", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsAvailable = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRollupInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRollupInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRollupInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RollupId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RollupId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRollupInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRollupInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRollupInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RollupInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RollupInfo == nil {
				m.RollupInfo = &RollupMetadata{}
			}
			if err := m.RollupInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRollupsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRollupsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRollupsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRollupsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRollupsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRollupsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rollups", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Rollups = append(m.Rollups, RollupMetadata{})
			if err := m.Rollups[len(m.Rollups)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRollupByMonikerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRollupByMonikerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRollupByMonikerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Moniker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Moniker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRollupByMonikerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRollupByMonikerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRollupByMonikerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RollupInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RollupInfo == nil {
				m.RollupInfo = &RollupMetadata{}
			}
			if err := m.RollupInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetBatchInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetBatchInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetBatchInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RollupId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RollupId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BatchNo", wireType)
			}
			m.BatchNo = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BatchNo |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetBatchInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetBatchInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetBatchInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BatchInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BatchInfo == nil {
				m.BatchInfo = &Batch{}
			}
			if err := m.BatchInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAllBatchesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAllBatchesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAllBatchesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RollupId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RollupId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Offset", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.XOffset = &QueryGetAllBatchesRequest_Offset{v}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.XLimit = &QueryGetAllBatchesRequest_Limit{v}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Order", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.XOrder = &QueryGetAllBatchesRequest_Order{string(dAtA[iNdEx:postIndex])}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAllBatchesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAllBatchesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAllBatchesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Batch", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Batch = append(m.Batch, Batch{})
			if err := m.Batch[len(m.Batch)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			m.Total = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Total |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Offset", wireType)
			}
			m.Offset = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Offset |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			m.Limit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Limit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Order", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Order = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
