// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package junction

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_VrfRecord                          protoreflect.MessageDescriptor
	fd_VrfRecord_vrfCreatorAddr           protoreflect.FieldDescriptor
	fd_VrfRecord_vrfVerifierAddr          protoreflect.FieldDescriptor
	fd_VrfRecord_podNumber                protoreflect.FieldDescriptor
	fd_VrfRecord_stationId                protoreflect.FieldDescriptor
	fd_VrfRecord_occupancy                protoreflect.FieldDescriptor
	fd_VrfRecord_creatorsVrfKey           protoreflect.FieldDescriptor
	fd_VrfRecord_serializedRcFromCreator  protoreflect.FieldDescriptor
	fd_VrfRecord_serializedRcFromVerifier protoreflect.FieldDescriptor
	fd_VrfRecord_proof                    protoreflect.FieldDescriptor
	fd_VrfRecord_vrfOutput                protoreflect.FieldDescriptor
	fd_VrfRecord_isVerified               protoreflect.FieldDescriptor
	fd_VrfRecord_vrn                      protoreflect.FieldDescriptor
)

func init() {
	file_junction_junction_vrf_record_proto_init()
	md_VrfRecord = File_junction_junction_vrf_record_proto.Messages().ByName("VrfRecord")
	fd_VrfRecord_vrfCreatorAddr = md_VrfRecord.Fields().ByName("vrfCreatorAddr")
	fd_VrfRecord_vrfVerifierAddr = md_VrfRecord.Fields().ByName("vrfVerifierAddr")
	fd_VrfRecord_podNumber = md_VrfRecord.Fields().ByName("podNumber")
	fd_VrfRecord_stationId = md_VrfRecord.Fields().ByName("stationId")
	fd_VrfRecord_occupancy = md_VrfRecord.Fields().ByName("occupancy")
	fd_VrfRecord_creatorsVrfKey = md_VrfRecord.Fields().ByName("creatorsVrfKey")
	fd_VrfRecord_serializedRcFromCreator = md_VrfRecord.Fields().ByName("serializedRcFromCreator")
	fd_VrfRecord_serializedRcFromVerifier = md_VrfRecord.Fields().ByName("serializedRcFromVerifier")
	fd_VrfRecord_proof = md_VrfRecord.Fields().ByName("proof")
	fd_VrfRecord_vrfOutput = md_VrfRecord.Fields().ByName("vrfOutput")
	fd_VrfRecord_isVerified = md_VrfRecord.Fields().ByName("isVerified")
	fd_VrfRecord_vrn = md_VrfRecord.Fields().ByName("vrn")
}

var _ protoreflect.Message = (*fastReflection_VrfRecord)(nil)

type fastReflection_VrfRecord VrfRecord

func (x *VrfRecord) ProtoReflect() protoreflect.Message {
	return (*fastReflection_VrfRecord)(x)
}

func (x *VrfRecord) slowProtoReflect() protoreflect.Message {
	mi := &file_junction_junction_vrf_record_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_VrfRecord_messageType fastReflection_VrfRecord_messageType
var _ protoreflect.MessageType = fastReflection_VrfRecord_messageType{}

type fastReflection_VrfRecord_messageType struct{}

func (x fastReflection_VrfRecord_messageType) Zero() protoreflect.Message {
	return (*fastReflection_VrfRecord)(nil)
}
func (x fastReflection_VrfRecord_messageType) New() protoreflect.Message {
	return new(fastReflection_VrfRecord)
}
func (x fastReflection_VrfRecord_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_VrfRecord
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_VrfRecord) Descriptor() protoreflect.MessageDescriptor {
	return md_VrfRecord
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_VrfRecord) Type() protoreflect.MessageType {
	return _fastReflection_VrfRecord_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_VrfRecord) New() protoreflect.Message {
	return new(fastReflection_VrfRecord)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_VrfRecord) Interface() protoreflect.ProtoMessage {
	return (*VrfRecord)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_VrfRecord) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.VrfCreatorAddr != "" {
		value := protoreflect.ValueOfString(x.VrfCreatorAddr)
		if !f(fd_VrfRecord_vrfCreatorAddr, value) {
			return
		}
	}
	if x.VrfVerifierAddr != "" {
		value := protoreflect.ValueOfString(x.VrfVerifierAddr)
		if !f(fd_VrfRecord_vrfVerifierAddr, value) {
			return
		}
	}
	if x.PodNumber != "" {
		value := protoreflect.ValueOfString(x.PodNumber)
		if !f(fd_VrfRecord_podNumber, value) {
			return
		}
	}
	if x.StationId != "" {
		value := protoreflect.ValueOfString(x.StationId)
		if !f(fd_VrfRecord_stationId, value) {
			return
		}
	}
	if x.Occupancy != "" {
		value := protoreflect.ValueOfString(x.Occupancy)
		if !f(fd_VrfRecord_occupancy, value) {
			return
		}
	}
	if x.CreatorsVrfKey != "" {
		value := protoreflect.ValueOfString(x.CreatorsVrfKey)
		if !f(fd_VrfRecord_creatorsVrfKey, value) {
			return
		}
	}
	if len(x.SerializedRcFromCreator) != 0 {
		value := protoreflect.ValueOfBytes(x.SerializedRcFromCreator)
		if !f(fd_VrfRecord_serializedRcFromCreator, value) {
			return
		}
	}
	if len(x.SerializedRcFromVerifier) != 0 {
		value := protoreflect.ValueOfBytes(x.SerializedRcFromVerifier)
		if !f(fd_VrfRecord_serializedRcFromVerifier, value) {
			return
		}
	}
	if len(x.Proof) != 0 {
		value := protoreflect.ValueOfBytes(x.Proof)
		if !f(fd_VrfRecord_proof, value) {
			return
		}
	}
	if len(x.VrfOutput) != 0 {
		value := protoreflect.ValueOfBytes(x.VrfOutput)
		if !f(fd_VrfRecord_vrfOutput, value) {
			return
		}
	}
	if x.IsVerified != false {
		value := protoreflect.ValueOfBool(x.IsVerified)
		if !f(fd_VrfRecord_isVerified, value) {
			return
		}
	}
	if len(x.Vrn) != 0 {
		value := protoreflect.ValueOfBytes(x.Vrn)
		if !f(fd_VrfRecord_vrn, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_VrfRecord) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "junction.junction.VrfRecord.vrfCreatorAddr":
		return x.VrfCreatorAddr != ""
	case "junction.junction.VrfRecord.vrfVerifierAddr":
		return x.VrfVerifierAddr != ""
	case "junction.junction.VrfRecord.podNumber":
		return x.PodNumber != ""
	case "junction.junction.VrfRecord.stationId":
		return x.StationId != ""
	case "junction.junction.VrfRecord.occupancy":
		return x.Occupancy != ""
	case "junction.junction.VrfRecord.creatorsVrfKey":
		return x.CreatorsVrfKey != ""
	case "junction.junction.VrfRecord.serializedRcFromCreator":
		return len(x.SerializedRcFromCreator) != 0
	case "junction.junction.VrfRecord.serializedRcFromVerifier":
		return len(x.SerializedRcFromVerifier) != 0
	case "junction.junction.VrfRecord.proof":
		return len(x.Proof) != 0
	case "junction.junction.VrfRecord.vrfOutput":
		return len(x.VrfOutput) != 0
	case "junction.junction.VrfRecord.isVerified":
		return x.IsVerified != false
	case "junction.junction.VrfRecord.vrn":
		return len(x.Vrn) != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: junction.junction.VrfRecord"))
		}
		panic(fmt.Errorf("message junction.junction.VrfRecord does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_VrfRecord) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "junction.junction.VrfRecord.vrfCreatorAddr":
		x.VrfCreatorAddr = ""
	case "junction.junction.VrfRecord.vrfVerifierAddr":
		x.VrfVerifierAddr = ""
	case "junction.junction.VrfRecord.podNumber":
		x.PodNumber = ""
	case "junction.junction.VrfRecord.stationId":
		x.StationId = ""
	case "junction.junction.VrfRecord.occupancy":
		x.Occupancy = ""
	case "junction.junction.VrfRecord.creatorsVrfKey":
		x.CreatorsVrfKey = ""
	case "junction.junction.VrfRecord.serializedRcFromCreator":
		x.SerializedRcFromCreator = nil
	case "junction.junction.VrfRecord.serializedRcFromVerifier":
		x.SerializedRcFromVerifier = nil
	case "junction.junction.VrfRecord.proof":
		x.Proof = nil
	case "junction.junction.VrfRecord.vrfOutput":
		x.VrfOutput = nil
	case "junction.junction.VrfRecord.isVerified":
		x.IsVerified = false
	case "junction.junction.VrfRecord.vrn":
		x.Vrn = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: junction.junction.VrfRecord"))
		}
		panic(fmt.Errorf("message junction.junction.VrfRecord does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_VrfRecord) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "junction.junction.VrfRecord.vrfCreatorAddr":
		value := x.VrfCreatorAddr
		return protoreflect.ValueOfString(value)
	case "junction.junction.VrfRecord.vrfVerifierAddr":
		value := x.VrfVerifierAddr
		return protoreflect.ValueOfString(value)
	case "junction.junction.VrfRecord.podNumber":
		value := x.PodNumber
		return protoreflect.ValueOfString(value)
	case "junction.junction.VrfRecord.stationId":
		value := x.StationId
		return protoreflect.ValueOfString(value)
	case "junction.junction.VrfRecord.occupancy":
		value := x.Occupancy
		return protoreflect.ValueOfString(value)
	case "junction.junction.VrfRecord.creatorsVrfKey":
		value := x.CreatorsVrfKey
		return protoreflect.ValueOfString(value)
	case "junction.junction.VrfRecord.serializedRcFromCreator":
		value := x.SerializedRcFromCreator
		return protoreflect.ValueOfBytes(value)
	case "junction.junction.VrfRecord.serializedRcFromVerifier":
		value := x.SerializedRcFromVerifier
		return protoreflect.ValueOfBytes(value)
	case "junction.junction.VrfRecord.proof":
		value := x.Proof
		return protoreflect.ValueOfBytes(value)
	case "junction.junction.VrfRecord.vrfOutput":
		value := x.VrfOutput
		return protoreflect.ValueOfBytes(value)
	case "junction.junction.VrfRecord.isVerified":
		value := x.IsVerified
		return protoreflect.ValueOfBool(value)
	case "junction.junction.VrfRecord.vrn":
		value := x.Vrn
		return protoreflect.ValueOfBytes(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: junction.junction.VrfRecord"))
		}
		panic(fmt.Errorf("message junction.junction.VrfRecord does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_VrfRecord) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "junction.junction.VrfRecord.vrfCreatorAddr":
		x.VrfCreatorAddr = value.Interface().(string)
	case "junction.junction.VrfRecord.vrfVerifierAddr":
		x.VrfVerifierAddr = value.Interface().(string)
	case "junction.junction.VrfRecord.podNumber":
		x.PodNumber = value.Interface().(string)
	case "junction.junction.VrfRecord.stationId":
		x.StationId = value.Interface().(string)
	case "junction.junction.VrfRecord.occupancy":
		x.Occupancy = value.Interface().(string)
	case "junction.junction.VrfRecord.creatorsVrfKey":
		x.CreatorsVrfKey = value.Interface().(string)
	case "junction.junction.VrfRecord.serializedRcFromCreator":
		x.SerializedRcFromCreator = value.Bytes()
	case "junction.junction.VrfRecord.serializedRcFromVerifier":
		x.SerializedRcFromVerifier = value.Bytes()
	case "junction.junction.VrfRecord.proof":
		x.Proof = value.Bytes()
	case "junction.junction.VrfRecord.vrfOutput":
		x.VrfOutput = value.Bytes()
	case "junction.junction.VrfRecord.isVerified":
		x.IsVerified = value.Bool()
	case "junction.junction.VrfRecord.vrn":
		x.Vrn = value.Bytes()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: junction.junction.VrfRecord"))
		}
		panic(fmt.Errorf("message junction.junction.VrfRecord does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_VrfRecord) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "junction.junction.VrfRecord.vrfCreatorAddr":
		panic(fmt.Errorf("field vrfCreatorAddr of message junction.junction.VrfRecord is not mutable"))
	case "junction.junction.VrfRecord.vrfVerifierAddr":
		panic(fmt.Errorf("field vrfVerifierAddr of message junction.junction.VrfRecord is not mutable"))
	case "junction.junction.VrfRecord.podNumber":
		panic(fmt.Errorf("field podNumber of message junction.junction.VrfRecord is not mutable"))
	case "junction.junction.VrfRecord.stationId":
		panic(fmt.Errorf("field stationId of message junction.junction.VrfRecord is not mutable"))
	case "junction.junction.VrfRecord.occupancy":
		panic(fmt.Errorf("field occupancy of message junction.junction.VrfRecord is not mutable"))
	case "junction.junction.VrfRecord.creatorsVrfKey":
		panic(fmt.Errorf("field creatorsVrfKey of message junction.junction.VrfRecord is not mutable"))
	case "junction.junction.VrfRecord.serializedRcFromCreator":
		panic(fmt.Errorf("field serializedRcFromCreator of message junction.junction.VrfRecord is not mutable"))
	case "junction.junction.VrfRecord.serializedRcFromVerifier":
		panic(fmt.Errorf("field serializedRcFromVerifier of message junction.junction.VrfRecord is not mutable"))
	case "junction.junction.VrfRecord.proof":
		panic(fmt.Errorf("field proof of message junction.junction.VrfRecord is not mutable"))
	case "junction.junction.VrfRecord.vrfOutput":
		panic(fmt.Errorf("field vrfOutput of message junction.junction.VrfRecord is not mutable"))
	case "junction.junction.VrfRecord.isVerified":
		panic(fmt.Errorf("field isVerified of message junction.junction.VrfRecord is not mutable"))
	case "junction.junction.VrfRecord.vrn":
		panic(fmt.Errorf("field vrn of message junction.junction.VrfRecord is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: junction.junction.VrfRecord"))
		}
		panic(fmt.Errorf("message junction.junction.VrfRecord does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_VrfRecord) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "junction.junction.VrfRecord.vrfCreatorAddr":
		return protoreflect.ValueOfString("")
	case "junction.junction.VrfRecord.vrfVerifierAddr":
		return protoreflect.ValueOfString("")
	case "junction.junction.VrfRecord.podNumber":
		return protoreflect.ValueOfString("")
	case "junction.junction.VrfRecord.stationId":
		return protoreflect.ValueOfString("")
	case "junction.junction.VrfRecord.occupancy":
		return protoreflect.ValueOfString("")
	case "junction.junction.VrfRecord.creatorsVrfKey":
		return protoreflect.ValueOfString("")
	case "junction.junction.VrfRecord.serializedRcFromCreator":
		return protoreflect.ValueOfBytes(nil)
	case "junction.junction.VrfRecord.serializedRcFromVerifier":
		return protoreflect.ValueOfBytes(nil)
	case "junction.junction.VrfRecord.proof":
		return protoreflect.ValueOfBytes(nil)
	case "junction.junction.VrfRecord.vrfOutput":
		return protoreflect.ValueOfBytes(nil)
	case "junction.junction.VrfRecord.isVerified":
		return protoreflect.ValueOfBool(false)
	case "junction.junction.VrfRecord.vrn":
		return protoreflect.ValueOfBytes(nil)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: junction.junction.VrfRecord"))
		}
		panic(fmt.Errorf("message junction.junction.VrfRecord does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_VrfRecord) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in junction.junction.VrfRecord", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_VrfRecord) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_VrfRecord) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_VrfRecord) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_VrfRecord) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*VrfRecord)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.VrfCreatorAddr)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.VrfVerifierAddr)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.PodNumber)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.StationId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Occupancy)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.CreatorsVrfKey)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.SerializedRcFromCreator)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.SerializedRcFromVerifier)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Proof)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.VrfOutput)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.IsVerified {
			n += 2
		}
		l = len(x.Vrn)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*VrfRecord)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Vrn) > 0 {
			i -= len(x.Vrn)
			copy(dAtA[i:], x.Vrn)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Vrn)))
			i--
			dAtA[i] = 0x62
		}
		if x.IsVerified {
			i--
			if x.IsVerified {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
			i--
			dAtA[i] = 0x58
		}
		if len(x.VrfOutput) > 0 {
			i -= len(x.VrfOutput)
			copy(dAtA[i:], x.VrfOutput)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.VrfOutput)))
			i--
			dAtA[i] = 0x52
		}
		if len(x.Proof) > 0 {
			i -= len(x.Proof)
			copy(dAtA[i:], x.Proof)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Proof)))
			i--
			dAtA[i] = 0x4a
		}
		if len(x.SerializedRcFromVerifier) > 0 {
			i -= len(x.SerializedRcFromVerifier)
			copy(dAtA[i:], x.SerializedRcFromVerifier)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.SerializedRcFromVerifier)))
			i--
			dAtA[i] = 0x42
		}
		if len(x.SerializedRcFromCreator) > 0 {
			i -= len(x.SerializedRcFromCreator)
			copy(dAtA[i:], x.SerializedRcFromCreator)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.SerializedRcFromCreator)))
			i--
			dAtA[i] = 0x3a
		}
		if len(x.CreatorsVrfKey) > 0 {
			i -= len(x.CreatorsVrfKey)
			copy(dAtA[i:], x.CreatorsVrfKey)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.CreatorsVrfKey)))
			i--
			dAtA[i] = 0x32
		}
		if len(x.Occupancy) > 0 {
			i -= len(x.Occupancy)
			copy(dAtA[i:], x.Occupancy)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Occupancy)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.StationId) > 0 {
			i -= len(x.StationId)
			copy(dAtA[i:], x.StationId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.StationId)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.PodNumber) > 0 {
			i -= len(x.PodNumber)
			copy(dAtA[i:], x.PodNumber)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.PodNumber)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.VrfVerifierAddr) > 0 {
			i -= len(x.VrfVerifierAddr)
			copy(dAtA[i:], x.VrfVerifierAddr)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.VrfVerifierAddr)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.VrfCreatorAddr) > 0 {
			i -= len(x.VrfCreatorAddr)
			copy(dAtA[i:], x.VrfCreatorAddr)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.VrfCreatorAddr)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*VrfRecord)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: VrfRecord: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: VrfRecord: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field VrfCreatorAddr", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.VrfCreatorAddr = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field VrfVerifierAddr", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.VrfVerifierAddr = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field PodNumber", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.PodNumber = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field StationId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.StationId = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Occupancy", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Occupancy = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field CreatorsVrfKey", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.CreatorsVrfKey = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 7:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SerializedRcFromCreator", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.SerializedRcFromCreator = append(x.SerializedRcFromCreator[:0], dAtA[iNdEx:postIndex]...)
				if x.SerializedRcFromCreator == nil {
					x.SerializedRcFromCreator = []byte{}
				}
				iNdEx = postIndex
			case 8:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SerializedRcFromVerifier", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.SerializedRcFromVerifier = append(x.SerializedRcFromVerifier[:0], dAtA[iNdEx:postIndex]...)
				if x.SerializedRcFromVerifier == nil {
					x.SerializedRcFromVerifier = []byte{}
				}
				iNdEx = postIndex
			case 9:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Proof = append(x.Proof[:0], dAtA[iNdEx:postIndex]...)
				if x.Proof == nil {
					x.Proof = []byte{}
				}
				iNdEx = postIndex
			case 10:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field VrfOutput", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.VrfOutput = append(x.VrfOutput[:0], dAtA[iNdEx:postIndex]...)
				if x.VrfOutput == nil {
					x.VrfOutput = []byte{}
				}
				iNdEx = postIndex
			case 11:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field IsVerified", wireType)
				}
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				x.IsVerified = bool(v != 0)
			case 12:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Vrn", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Vrn = append(x.Vrn[:0], dAtA[iNdEx:postIndex]...)
				if x.Vrn == nil {
					x.Vrn = []byte{}
				}
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: junction/junction/vrf_record.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VrfRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VrfCreatorAddr           string `protobuf:"bytes,1,opt,name=vrfCreatorAddr,proto3" json:"vrfCreatorAddr,omitempty"`
	VrfVerifierAddr          string `protobuf:"bytes,2,opt,name=vrfVerifierAddr,proto3" json:"vrfVerifierAddr,omitempty"`
	PodNumber                string `protobuf:"bytes,3,opt,name=podNumber,proto3" json:"podNumber,omitempty"`
	StationId                string `protobuf:"bytes,4,opt,name=stationId,proto3" json:"stationId,omitempty"`
	Occupancy                string `protobuf:"bytes,5,opt,name=occupancy,proto3" json:"occupancy,omitempty"`
	CreatorsVrfKey           string `protobuf:"bytes,6,opt,name=creatorsVrfKey,proto3" json:"creatorsVrfKey,omitempty"`
	SerializedRcFromCreator  []byte `protobuf:"bytes,7,opt,name=serializedRcFromCreator,proto3" json:"serializedRcFromCreator,omitempty"`
	SerializedRcFromVerifier []byte `protobuf:"bytes,8,opt,name=serializedRcFromVerifier,proto3" json:"serializedRcFromVerifier,omitempty"`
	Proof                    []byte `protobuf:"bytes,9,opt,name=proof,proto3" json:"proof,omitempty"`
	VrfOutput                []byte `protobuf:"bytes,10,opt,name=vrfOutput,proto3" json:"vrfOutput,omitempty"`
	IsVerified               bool   `protobuf:"varint,11,opt,name=isVerified,proto3" json:"isVerified,omitempty"`
	Vrn                      []byte `protobuf:"bytes,12,opt,name=vrn,proto3" json:"vrn,omitempty"`
}

func (x *VrfRecord) Reset() {
	*x = VrfRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_junction_junction_vrf_record_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VrfRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VrfRecord) ProtoMessage() {}

// Deprecated: Use VrfRecord.ProtoReflect.Descriptor instead.
func (*VrfRecord) Descriptor() ([]byte, []int) {
	return file_junction_junction_vrf_record_proto_rawDescGZIP(), []int{0}
}

func (x *VrfRecord) GetVrfCreatorAddr() string {
	if x != nil {
		return x.VrfCreatorAddr
	}
	return ""
}

func (x *VrfRecord) GetVrfVerifierAddr() string {
	if x != nil {
		return x.VrfVerifierAddr
	}
	return ""
}

func (x *VrfRecord) GetPodNumber() string {
	if x != nil {
		return x.PodNumber
	}
	return ""
}

func (x *VrfRecord) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *VrfRecord) GetOccupancy() string {
	if x != nil {
		return x.Occupancy
	}
	return ""
}

func (x *VrfRecord) GetCreatorsVrfKey() string {
	if x != nil {
		return x.CreatorsVrfKey
	}
	return ""
}

func (x *VrfRecord) GetSerializedRcFromCreator() []byte {
	if x != nil {
		return x.SerializedRcFromCreator
	}
	return nil
}

func (x *VrfRecord) GetSerializedRcFromVerifier() []byte {
	if x != nil {
		return x.SerializedRcFromVerifier
	}
	return nil
}

func (x *VrfRecord) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *VrfRecord) GetVrfOutput() []byte {
	if x != nil {
		return x.VrfOutput
	}
	return nil
}

func (x *VrfRecord) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *VrfRecord) GetVrn() []byte {
	if x != nil {
		return x.Vrn
	}
	return nil
}

var File_junction_junction_vrf_record_proto protoreflect.FileDescriptor

var file_junction_junction_vrf_record_proto_rawDesc = []byte{
	0x0a, 0x22, 0x6a, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x6a, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x72, 0x66, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x6a, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x6a,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xbb, 0x03, 0x0a, 0x09, 0x56, 0x72, 0x66, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x76, 0x72, 0x66, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x76,
	0x72, 0x66, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x72, 0x12, 0x28, 0x0a,
	0x0f, 0x76, 0x72, 0x66, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x76, 0x72, 0x66, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6f, 0x64, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6f, 0x64, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x63, 0x63, 0x75, 0x70, 0x61, 0x6e, 0x63, 0x79,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x63, 0x63, 0x75, 0x70, 0x61, 0x6e, 0x63,
	0x79, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x56, 0x72, 0x66,
	0x4b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x6f, 0x72, 0x73, 0x56, 0x72, 0x66, 0x4b, 0x65, 0x79, 0x12, 0x38, 0x0a, 0x17, 0x73, 0x65, 0x72,
	0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x52, 0x63, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x6f, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x17, 0x73, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x52, 0x63, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x6f, 0x72, 0x12, 0x3a, 0x0a, 0x18, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65,
	0x64, 0x52, 0x63, 0x46, 0x72, 0x6f, 0x6d, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x18, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65,
	0x64, 0x52, 0x63, 0x46, 0x72, 0x6f, 0x6d, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x70, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x72, 0x66, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x76, 0x72, 0x66, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x73, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65,
	0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x72, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x03, 0x76, 0x72, 0x6e, 0x42, 0xb0, 0x01, 0x0a, 0x15, 0x63, 0x6f, 0x6d, 0x2e, 0x6a, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x6a, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42,
	0x0e, 0x56, 0x72, 0x66, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x22, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x6a, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x6a, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0xa2, 0x02, 0x03, 0x4a, 0x4a, 0x58, 0xaa, 0x02, 0x11, 0x4a, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4a, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0xca,
	0x02, 0x11, 0x4a, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5c, 0x4a, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0xe2, 0x02, 0x1d, 0x4a, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5c, 0x4a,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0xea, 0x02, 0x12, 0x4a, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x3a, 0x3a,
	0x4a, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_junction_junction_vrf_record_proto_rawDescOnce sync.Once
	file_junction_junction_vrf_record_proto_rawDescData = file_junction_junction_vrf_record_proto_rawDesc
)

func file_junction_junction_vrf_record_proto_rawDescGZIP() []byte {
	file_junction_junction_vrf_record_proto_rawDescOnce.Do(func() {
		file_junction_junction_vrf_record_proto_rawDescData = protoimpl.X.CompressGZIP(file_junction_junction_vrf_record_proto_rawDescData)
	})
	return file_junction_junction_vrf_record_proto_rawDescData
}

var file_junction_junction_vrf_record_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_junction_junction_vrf_record_proto_goTypes = []interface{}{
	(*VrfRecord)(nil), // 0: junction.junction.VrfRecord
}
var file_junction_junction_vrf_record_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_junction_junction_vrf_record_proto_init() }
func file_junction_junction_vrf_record_proto_init() {
	if File_junction_junction_vrf_record_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_junction_junction_vrf_record_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VrfRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_junction_junction_vrf_record_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_junction_junction_vrf_record_proto_goTypes,
		DependencyIndexes: file_junction_junction_vrf_record_proto_depIdxs,
		MessageInfos:      file_junction_junction_vrf_record_proto_msgTypes,
	}.Build()
	File_junction_junction_vrf_record_proto = out.File
	file_junction_junction_vrf_record_proto_rawDesc = nil
	file_junction_junction_vrf_record_proto_goTypes = nil
	file_junction_junction_vrf_record_proto_depIdxs = nil
}
