version: v1
plugins:
  - name: openapiv2
    out: ./docs/client
    opt:
      - logtostderr=true
      - openapi_naming_strategy=fqn
      - json_names_for_fields=false
      - generate_unbound_methods=true
