// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: junction/zksequencer/tx.proto

package zksequencer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Msg_UpdateParams_FullMethodName             = "/junction.zksequencer.Msg/UpdateParams"
	Msg_CreateCollege_FullMethodName            = "/junction.zksequencer.Msg/CreateCollege"
	Msg_UpdateCollege_FullMethodName            = "/junction.zksequencer.Msg/UpdateCollege"
	Msg_DeleteCollege_FullMethodName            = "/junction.zksequencer.Msg/DeleteCollege"
	Msg_AddStudentViaZksequencer_FullMethodName = "/junction.zksequencer.Msg/AddStudentViaZksequencer"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	CreateCollege(ctx context.Context, in *MsgCreateCollege, opts ...grpc.CallOption) (*MsgCreateCollegeResponse, error)
	UpdateCollege(ctx context.Context, in *MsgUpdateCollege, opts ...grpc.CallOption) (*MsgUpdateCollegeResponse, error)
	DeleteCollege(ctx context.Context, in *MsgDeleteCollege, opts ...grpc.CallOption) (*MsgDeleteCollegeResponse, error)
	AddStudentViaZksequencer(ctx context.Context, in *MsgAddStudentViaZksequencer, opts ...grpc.CallOption) (*MsgAddStudentViaZksequencerResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateCollege(ctx context.Context, in *MsgCreateCollege, opts ...grpc.CallOption) (*MsgCreateCollegeResponse, error) {
	out := new(MsgCreateCollegeResponse)
	err := c.cc.Invoke(ctx, Msg_CreateCollege_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateCollege(ctx context.Context, in *MsgUpdateCollege, opts ...grpc.CallOption) (*MsgUpdateCollegeResponse, error) {
	out := new(MsgUpdateCollegeResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateCollege_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteCollege(ctx context.Context, in *MsgDeleteCollege, opts ...grpc.CallOption) (*MsgDeleteCollegeResponse, error) {
	out := new(MsgDeleteCollegeResponse)
	err := c.cc.Invoke(ctx, Msg_DeleteCollege_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AddStudentViaZksequencer(ctx context.Context, in *MsgAddStudentViaZksequencer, opts ...grpc.CallOption) (*MsgAddStudentViaZksequencerResponse, error) {
	out := new(MsgAddStudentViaZksequencerResponse)
	err := c.cc.Invoke(ctx, Msg_AddStudentViaZksequencer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	CreateCollege(context.Context, *MsgCreateCollege) (*MsgCreateCollegeResponse, error)
	UpdateCollege(context.Context, *MsgUpdateCollege) (*MsgUpdateCollegeResponse, error)
	DeleteCollege(context.Context, *MsgDeleteCollege) (*MsgDeleteCollegeResponse, error)
	AddStudentViaZksequencer(context.Context, *MsgAddStudentViaZksequencer) (*MsgAddStudentViaZksequencerResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) CreateCollege(context.Context, *MsgCreateCollege) (*MsgCreateCollegeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCollege not implemented")
}
func (UnimplementedMsgServer) UpdateCollege(context.Context, *MsgUpdateCollege) (*MsgUpdateCollegeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCollege not implemented")
}
func (UnimplementedMsgServer) DeleteCollege(context.Context, *MsgDeleteCollege) (*MsgDeleteCollegeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCollege not implemented")
}
func (UnimplementedMsgServer) AddStudentViaZksequencer(context.Context, *MsgAddStudentViaZksequencer) (*MsgAddStudentViaZksequencerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddStudentViaZksequencer not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateCollege_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateCollege)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateCollege(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CreateCollege_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateCollege(ctx, req.(*MsgCreateCollege))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateCollege_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateCollege)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateCollege(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateCollege_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateCollege(ctx, req.(*MsgUpdateCollege))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteCollege_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteCollege)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteCollege(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_DeleteCollege_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteCollege(ctx, req.(*MsgDeleteCollege))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AddStudentViaZksequencer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddStudentViaZksequencer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddStudentViaZksequencer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_AddStudentViaZksequencer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddStudentViaZksequencer(ctx, req.(*MsgAddStudentViaZksequencer))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "junction.zksequencer.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "CreateCollege",
			Handler:    _Msg_CreateCollege_Handler,
		},
		{
			MethodName: "UpdateCollege",
			Handler:    _Msg_UpdateCollege_Handler,
		},
		{
			MethodName: "DeleteCollege",
			Handler:    _Msg_DeleteCollege_Handler,
		},
		{
			MethodName: "AddStudentViaZksequencer",
			Handler:    _Msg_AddStudentViaZksequencer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "junction/zksequencer/tx.proto",
}
